/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.currency.service.base;

import com.liferay.commerce.currency.model.CommerceCurrency;
import com.liferay.commerce.currency.service.CommerceCurrencyService;
import com.liferay.commerce.currency.service.CommerceCurrencyServiceUtil;
import com.liferay.commerce.currency.service.persistence.CommerceCurrencyFinder;
import com.liferay.commerce.currency.service.persistence.CommerceCurrencyPersistence;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.lang.reflect.Field;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the commerce currency remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.commerce.currency.service.impl.CommerceCurrencyServiceImpl}.
 * </p>
 *
 * @author Andrea Di Giorgi
 * @see com.liferay.commerce.currency.service.impl.CommerceCurrencyServiceImpl
 * @generated
 */
public abstract class CommerceCurrencyServiceBaseImpl
	extends BaseServiceImpl
	implements CommerceCurrencyService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CommerceCurrencyService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>CommerceCurrencyServiceUtil</code>.
	 */

	/**
	 * Returns the commerce currency local service.
	 *
	 * @return the commerce currency local service
	 */
	public com.liferay.commerce.currency.service.CommerceCurrencyLocalService
		getCommerceCurrencyLocalService() {

		return commerceCurrencyLocalService;
	}

	/**
	 * Sets the commerce currency local service.
	 *
	 * @param commerceCurrencyLocalService the commerce currency local service
	 */
	public void setCommerceCurrencyLocalService(
		com.liferay.commerce.currency.service.CommerceCurrencyLocalService
			commerceCurrencyLocalService) {

		this.commerceCurrencyLocalService = commerceCurrencyLocalService;
	}

	/**
	 * Returns the commerce currency remote service.
	 *
	 * @return the commerce currency remote service
	 */
	public CommerceCurrencyService getCommerceCurrencyService() {
		return commerceCurrencyService;
	}

	/**
	 * Sets the commerce currency remote service.
	 *
	 * @param commerceCurrencyService the commerce currency remote service
	 */
	public void setCommerceCurrencyService(
		CommerceCurrencyService commerceCurrencyService) {

		this.commerceCurrencyService = commerceCurrencyService;
	}

	/**
	 * Returns the commerce currency persistence.
	 *
	 * @return the commerce currency persistence
	 */
	public CommerceCurrencyPersistence getCommerceCurrencyPersistence() {
		return commerceCurrencyPersistence;
	}

	/**
	 * Sets the commerce currency persistence.
	 *
	 * @param commerceCurrencyPersistence the commerce currency persistence
	 */
	public void setCommerceCurrencyPersistence(
		CommerceCurrencyPersistence commerceCurrencyPersistence) {

		this.commerceCurrencyPersistence = commerceCurrencyPersistence;
	}

	/**
	 * Returns the commerce currency finder.
	 *
	 * @return the commerce currency finder
	 */
	public CommerceCurrencyFinder getCommerceCurrencyFinder() {
		return commerceCurrencyFinder;
	}

	/**
	 * Sets the commerce currency finder.
	 *
	 * @param commerceCurrencyFinder the commerce currency finder
	 */
	public void setCommerceCurrencyFinder(
		CommerceCurrencyFinder commerceCurrencyFinder) {

		this.commerceCurrencyFinder = commerceCurrencyFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		_setServiceUtilService(commerceCurrencyService);
	}

	public void destroy() {
		_setServiceUtilService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CommerceCurrencyService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CommerceCurrency.class;
	}

	protected String getModelClassName() {
		return CommerceCurrency.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = commerceCurrencyPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		CommerceCurrencyService commerceCurrencyService) {

		try {
			Field field = CommerceCurrencyServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, commerceCurrencyService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@BeanReference(
		type = com.liferay.commerce.currency.service.CommerceCurrencyLocalService.class
	)
	protected com.liferay.commerce.currency.service.CommerceCurrencyLocalService
		commerceCurrencyLocalService;

	@BeanReference(type = CommerceCurrencyService.class)
	protected CommerceCurrencyService commerceCurrencyService;

	@BeanReference(type = CommerceCurrencyPersistence.class)
	protected CommerceCurrencyPersistence commerceCurrencyPersistence;

	@BeanReference(type = CommerceCurrencyFinder.class)
	protected CommerceCurrencyFinder commerceCurrencyFinder;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		CommerceCurrencyServiceBaseImpl.class);

}