apiDir: "../headless-portal-instances-api/src/main/java"
apiPackagePath: "com.liferay.headless.portal.instances"
application:
    baseURI: "/headless-portal-instances"
    className: "HeadlessPortalInstancesApplication"
    name: "Liferay.Headless.Portal.Instances"
author: "Alberto Chaparro"
clientDir: "../headless-portal-instances-client/src/main/java"
forcePredictableOperationId: true
generateBatch: false
generateGraphQL: false