/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.notifications.admin.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the NotificationsQueueEntry service. Represents a row in the &quot;NotificationsQueueEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.notifications.admin.model.impl.NotificationsQueueEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.notifications.admin.model.impl.NotificationsQueueEntryImpl</code>.
 * </p>
 *
 * @author Gabriel Albuquerque
 * @see NotificationsQueueEntry
 * @generated
 */
@ProviderType
public interface NotificationsQueueEntryModel
	extends AttachedModel, BaseModel<NotificationsQueueEntry>, GroupedModel,
			MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a notifications queue entry model instance should use the {@link NotificationsQueueEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this notifications queue entry.
	 *
	 * @return the primary key of this notifications queue entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this notifications queue entry.
	 *
	 * @param primaryKey the primary key of this notifications queue entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this notifications queue entry.
	 *
	 * @return the mvcc version of this notifications queue entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this notifications queue entry.
	 *
	 * @param mvccVersion the mvcc version of this notifications queue entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the notifications queue entry ID of this notifications queue entry.
	 *
	 * @return the notifications queue entry ID of this notifications queue entry
	 */
	public long getNotificationsQueueEntryId();

	/**
	 * Sets the notifications queue entry ID of this notifications queue entry.
	 *
	 * @param notificationsQueueEntryId the notifications queue entry ID of this notifications queue entry
	 */
	public void setNotificationsQueueEntryId(long notificationsQueueEntryId);

	/**
	 * Returns the group ID of this notifications queue entry.
	 *
	 * @return the group ID of this notifications queue entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this notifications queue entry.
	 *
	 * @param groupId the group ID of this notifications queue entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this notifications queue entry.
	 *
	 * @return the company ID of this notifications queue entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this notifications queue entry.
	 *
	 * @param companyId the company ID of this notifications queue entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this notifications queue entry.
	 *
	 * @return the user ID of this notifications queue entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this notifications queue entry.
	 *
	 * @param userId the user ID of this notifications queue entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this notifications queue entry.
	 *
	 * @return the user uuid of this notifications queue entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this notifications queue entry.
	 *
	 * @param userUuid the user uuid of this notifications queue entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this notifications queue entry.
	 *
	 * @return the user name of this notifications queue entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this notifications queue entry.
	 *
	 * @param userName the user name of this notifications queue entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this notifications queue entry.
	 *
	 * @return the create date of this notifications queue entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this notifications queue entry.
	 *
	 * @param createDate the create date of this notifications queue entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this notifications queue entry.
	 *
	 * @return the modified date of this notifications queue entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this notifications queue entry.
	 *
	 * @param modifiedDate the modified date of this notifications queue entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this notifications queue entry.
	 *
	 * @return the fully qualified class name of this notifications queue entry
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this notifications queue entry.
	 *
	 * @return the class name ID of this notifications queue entry
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this notifications queue entry.
	 *
	 * @param classNameId the class name ID of this notifications queue entry
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this notifications queue entry.
	 *
	 * @return the class pk of this notifications queue entry
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this notifications queue entry.
	 *
	 * @param classPK the class pk of this notifications queue entry
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the notifications template ID of this notifications queue entry.
	 *
	 * @return the notifications template ID of this notifications queue entry
	 */
	public long getNotificationsTemplateId();

	/**
	 * Sets the notifications template ID of this notifications queue entry.
	 *
	 * @param notificationsTemplateId the notifications template ID of this notifications queue entry
	 */
	public void setNotificationsTemplateId(long notificationsTemplateId);

	/**
	 * Returns the from of this notifications queue entry.
	 *
	 * @return the from of this notifications queue entry
	 */
	@AutoEscape
	public String getFrom();

	/**
	 * Sets the from of this notifications queue entry.
	 *
	 * @param from the from of this notifications queue entry
	 */
	public void setFrom(String from);

	/**
	 * Returns the from name of this notifications queue entry.
	 *
	 * @return the from name of this notifications queue entry
	 */
	@AutoEscape
	public String getFromName();

	/**
	 * Sets the from name of this notifications queue entry.
	 *
	 * @param fromName the from name of this notifications queue entry
	 */
	public void setFromName(String fromName);

	/**
	 * Returns the to of this notifications queue entry.
	 *
	 * @return the to of this notifications queue entry
	 */
	@AutoEscape
	public String getTo();

	/**
	 * Sets the to of this notifications queue entry.
	 *
	 * @param to the to of this notifications queue entry
	 */
	public void setTo(String to);

	/**
	 * Returns the to name of this notifications queue entry.
	 *
	 * @return the to name of this notifications queue entry
	 */
	@AutoEscape
	public String getToName();

	/**
	 * Sets the to name of this notifications queue entry.
	 *
	 * @param toName the to name of this notifications queue entry
	 */
	public void setToName(String toName);

	/**
	 * Returns the cc of this notifications queue entry.
	 *
	 * @return the cc of this notifications queue entry
	 */
	@AutoEscape
	public String getCc();

	/**
	 * Sets the cc of this notifications queue entry.
	 *
	 * @param cc the cc of this notifications queue entry
	 */
	public void setCc(String cc);

	/**
	 * Returns the bcc of this notifications queue entry.
	 *
	 * @return the bcc of this notifications queue entry
	 */
	@AutoEscape
	public String getBcc();

	/**
	 * Sets the bcc of this notifications queue entry.
	 *
	 * @param bcc the bcc of this notifications queue entry
	 */
	public void setBcc(String bcc);

	/**
	 * Returns the subject of this notifications queue entry.
	 *
	 * @return the subject of this notifications queue entry
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this notifications queue entry.
	 *
	 * @param subject the subject of this notifications queue entry
	 */
	public void setSubject(String subject);

	/**
	 * Returns the body of this notifications queue entry.
	 *
	 * @return the body of this notifications queue entry
	 */
	@AutoEscape
	public String getBody();

	/**
	 * Sets the body of this notifications queue entry.
	 *
	 * @param body the body of this notifications queue entry
	 */
	public void setBody(String body);

	/**
	 * Returns the priority of this notifications queue entry.
	 *
	 * @return the priority of this notifications queue entry
	 */
	public double getPriority();

	/**
	 * Sets the priority of this notifications queue entry.
	 *
	 * @param priority the priority of this notifications queue entry
	 */
	public void setPriority(double priority);

	/**
	 * Returns the sent of this notifications queue entry.
	 *
	 * @return the sent of this notifications queue entry
	 */
	public boolean getSent();

	/**
	 * Returns <code>true</code> if this notifications queue entry is sent.
	 *
	 * @return <code>true</code> if this notifications queue entry is sent; <code>false</code> otherwise
	 */
	public boolean isSent();

	/**
	 * Sets whether this notifications queue entry is sent.
	 *
	 * @param sent the sent of this notifications queue entry
	 */
	public void setSent(boolean sent);

	/**
	 * Returns the sent date of this notifications queue entry.
	 *
	 * @return the sent date of this notifications queue entry
	 */
	public Date getSentDate();

	/**
	 * Sets the sent date of this notifications queue entry.
	 *
	 * @param sentDate the sent date of this notifications queue entry
	 */
	public void setSentDate(Date sentDate);

	@Override
	public NotificationsQueueEntry cloneWithOriginalValues();

}