/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.oauth.client.persistence.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the OAuthClientAuthServer service. Represents a row in the &quot;OAuthClientAuthServer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.oauth.client.persistence.model.impl.OAuthClientAuthServerModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.oauth.client.persistence.model.impl.OAuthClientAuthServerImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OAuthClientAuthServer
 * @generated
 */
@ProviderType
public interface OAuthClientAuthServerModel
	extends AuditedModel, BaseModel<OAuthClientAuthServer>, MVCCModel,
			ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a o auth client auth server model instance should use the {@link OAuthClientAuthServer} interface instead.
	 */

	/**
	 * Returns the primary key of this o auth client auth server.
	 *
	 * @return the primary key of this o auth client auth server
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this o auth client auth server.
	 *
	 * @param primaryKey the primary key of this o auth client auth server
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this o auth client auth server.
	 *
	 * @return the mvcc version of this o auth client auth server
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this o auth client auth server.
	 *
	 * @param mvccVersion the mvcc version of this o auth client auth server
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the o auth client auth server ID of this o auth client auth server.
	 *
	 * @return the o auth client auth server ID of this o auth client auth server
	 */
	public long getOAuthClientAuthServerId();

	/**
	 * Sets the o auth client auth server ID of this o auth client auth server.
	 *
	 * @param oAuthClientAuthServerId the o auth client auth server ID of this o auth client auth server
	 */
	public void setOAuthClientAuthServerId(long oAuthClientAuthServerId);

	/**
	 * Returns the company ID of this o auth client auth server.
	 *
	 * @return the company ID of this o auth client auth server
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this o auth client auth server.
	 *
	 * @param companyId the company ID of this o auth client auth server
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this o auth client auth server.
	 *
	 * @return the user ID of this o auth client auth server
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this o auth client auth server.
	 *
	 * @param userId the user ID of this o auth client auth server
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this o auth client auth server.
	 *
	 * @return the user uuid of this o auth client auth server
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this o auth client auth server.
	 *
	 * @param userUuid the user uuid of this o auth client auth server
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this o auth client auth server.
	 *
	 * @return the user name of this o auth client auth server
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this o auth client auth server.
	 *
	 * @param userName the user name of this o auth client auth server
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this o auth client auth server.
	 *
	 * @return the create date of this o auth client auth server
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this o auth client auth server.
	 *
	 * @param createDate the create date of this o auth client auth server
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this o auth client auth server.
	 *
	 * @return the modified date of this o auth client auth server
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this o auth client auth server.
	 *
	 * @param modifiedDate the modified date of this o auth client auth server
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the discovery endpoint of this o auth client auth server.
	 *
	 * @return the discovery endpoint of this o auth client auth server
	 */
	@AutoEscape
	public String getDiscoveryEndpoint();

	/**
	 * Sets the discovery endpoint of this o auth client auth server.
	 *
	 * @param discoveryEndpoint the discovery endpoint of this o auth client auth server
	 */
	public void setDiscoveryEndpoint(String discoveryEndpoint);

	/**
	 * Returns the issuer of this o auth client auth server.
	 *
	 * @return the issuer of this o auth client auth server
	 */
	@AutoEscape
	public String getIssuer();

	/**
	 * Sets the issuer of this o auth client auth server.
	 *
	 * @param issuer the issuer of this o auth client auth server
	 */
	public void setIssuer(String issuer);

	/**
	 * Returns the metadata json of this o auth client auth server.
	 *
	 * @return the metadata json of this o auth client auth server
	 */
	@AutoEscape
	public String getMetadataJSON();

	/**
	 * Sets the metadata json of this o auth client auth server.
	 *
	 * @param metadataJSON the metadata json of this o auth client auth server
	 */
	public void setMetadataJSON(String metadataJSON);

	/**
	 * Returns the type of this o auth client auth server.
	 *
	 * @return the type of this o auth client auth server
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this o auth client auth server.
	 *
	 * @param type the type of this o auth client auth server
	 */
	public void setType(String type);

	@Override
	public OAuthClientAuthServer cloneWithOriginalValues();

}