/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.shipping.engine.fixed.service.base;

import com.liferay.commerce.shipping.engine.fixed.model.CommerceShippingFixedOptionQualifier;
import com.liferay.commerce.shipping.engine.fixed.service.CommerceShippingFixedOptionQualifierService;
import com.liferay.commerce.shipping.engine.fixed.service.CommerceShippingFixedOptionQualifierServiceUtil;
import com.liferay.commerce.shipping.engine.fixed.service.persistence.CommerceShippingFixedOptionQualifierPersistence;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.lang.reflect.Field;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the commerce shipping fixed option qualifier remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.commerce.shipping.engine.fixed.service.impl.CommerceShippingFixedOptionQualifierServiceImpl}.
 * </p>
 *
 * @author Alessio Antonio Rendina
 * @see com.liferay.commerce.shipping.engine.fixed.service.impl.CommerceShippingFixedOptionQualifierServiceImpl
 * @generated
 */
public abstract class CommerceShippingFixedOptionQualifierServiceBaseImpl
	extends BaseServiceImpl
	implements CommerceShippingFixedOptionQualifierService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CommerceShippingFixedOptionQualifierService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>CommerceShippingFixedOptionQualifierServiceUtil</code>.
	 */

	/**
	 * Returns the commerce shipping fixed option qualifier local service.
	 *
	 * @return the commerce shipping fixed option qualifier local service
	 */
	public com.liferay.commerce.shipping.engine.fixed.service.
		CommerceShippingFixedOptionQualifierLocalService
			getCommerceShippingFixedOptionQualifierLocalService() {

		return commerceShippingFixedOptionQualifierLocalService;
	}

	/**
	 * Sets the commerce shipping fixed option qualifier local service.
	 *
	 * @param commerceShippingFixedOptionQualifierLocalService the commerce shipping fixed option qualifier local service
	 */
	public void setCommerceShippingFixedOptionQualifierLocalService(
		com.liferay.commerce.shipping.engine.fixed.service.
			CommerceShippingFixedOptionQualifierLocalService
				commerceShippingFixedOptionQualifierLocalService) {

		this.commerceShippingFixedOptionQualifierLocalService =
			commerceShippingFixedOptionQualifierLocalService;
	}

	/**
	 * Returns the commerce shipping fixed option qualifier remote service.
	 *
	 * @return the commerce shipping fixed option qualifier remote service
	 */
	public CommerceShippingFixedOptionQualifierService
		getCommerceShippingFixedOptionQualifierService() {

		return commerceShippingFixedOptionQualifierService;
	}

	/**
	 * Sets the commerce shipping fixed option qualifier remote service.
	 *
	 * @param commerceShippingFixedOptionQualifierService the commerce shipping fixed option qualifier remote service
	 */
	public void setCommerceShippingFixedOptionQualifierService(
		CommerceShippingFixedOptionQualifierService
			commerceShippingFixedOptionQualifierService) {

		this.commerceShippingFixedOptionQualifierService =
			commerceShippingFixedOptionQualifierService;
	}

	/**
	 * Returns the commerce shipping fixed option qualifier persistence.
	 *
	 * @return the commerce shipping fixed option qualifier persistence
	 */
	public CommerceShippingFixedOptionQualifierPersistence
		getCommerceShippingFixedOptionQualifierPersistence() {

		return commerceShippingFixedOptionQualifierPersistence;
	}

	/**
	 * Sets the commerce shipping fixed option qualifier persistence.
	 *
	 * @param commerceShippingFixedOptionQualifierPersistence the commerce shipping fixed option qualifier persistence
	 */
	public void setCommerceShippingFixedOptionQualifierPersistence(
		CommerceShippingFixedOptionQualifierPersistence
			commerceShippingFixedOptionQualifierPersistence) {

		this.commerceShippingFixedOptionQualifierPersistence =
			commerceShippingFixedOptionQualifierPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		_setServiceUtilService(commerceShippingFixedOptionQualifierService);
	}

	public void destroy() {
		_setServiceUtilService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CommerceShippingFixedOptionQualifierService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CommerceShippingFixedOptionQualifier.class;
	}

	protected String getModelClassName() {
		return CommerceShippingFixedOptionQualifier.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				commerceShippingFixedOptionQualifierPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		CommerceShippingFixedOptionQualifierService
			commerceShippingFixedOptionQualifierService) {

		try {
			Field field =
				CommerceShippingFixedOptionQualifierServiceUtil.class.
					getDeclaredField("_service");

			field.setAccessible(true);

			field.set(null, commerceShippingFixedOptionQualifierService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@BeanReference(
		type = com.liferay.commerce.shipping.engine.fixed.service.CommerceShippingFixedOptionQualifierLocalService.class
	)
	protected com.liferay.commerce.shipping.engine.fixed.service.
		CommerceShippingFixedOptionQualifierLocalService
			commerceShippingFixedOptionQualifierLocalService;

	@BeanReference(type = CommerceShippingFixedOptionQualifierService.class)
	protected CommerceShippingFixedOptionQualifierService
		commerceShippingFixedOptionQualifierService;

	@BeanReference(type = CommerceShippingFixedOptionQualifierPersistence.class)
	protected CommerceShippingFixedOptionQualifierPersistence
		commerceShippingFixedOptionQualifierPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

}