/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.qualifier.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CommerceQualifierEntry service. Represents a row in the &quot;CommerceQualifierEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.commerce.qualifier.model.impl.CommerceQualifierEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.commerce.qualifier.model.impl.CommerceQualifierEntryImpl</code>.
 * </p>
 *
 * @author Riccardo Alberti
 * @see CommerceQualifierEntry
 * @generated
 */
@ProviderType
public interface CommerceQualifierEntryModel
	extends AuditedModel, BaseModel<CommerceQualifierEntry>, MVCCModel,
			ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a commerce qualifier entry model instance should use the {@link CommerceQualifierEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this commerce qualifier entry.
	 *
	 * @return the primary key of this commerce qualifier entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this commerce qualifier entry.
	 *
	 * @param primaryKey the primary key of this commerce qualifier entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this commerce qualifier entry.
	 *
	 * @return the mvcc version of this commerce qualifier entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this commerce qualifier entry.
	 *
	 * @param mvccVersion the mvcc version of this commerce qualifier entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the commerce qualifier entry ID of this commerce qualifier entry.
	 *
	 * @return the commerce qualifier entry ID of this commerce qualifier entry
	 */
	public long getCommerceQualifierEntryId();

	/**
	 * Sets the commerce qualifier entry ID of this commerce qualifier entry.
	 *
	 * @param commerceQualifierEntryId the commerce qualifier entry ID of this commerce qualifier entry
	 */
	public void setCommerceQualifierEntryId(long commerceQualifierEntryId);

	/**
	 * Returns the company ID of this commerce qualifier entry.
	 *
	 * @return the company ID of this commerce qualifier entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this commerce qualifier entry.
	 *
	 * @param companyId the company ID of this commerce qualifier entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this commerce qualifier entry.
	 *
	 * @return the user ID of this commerce qualifier entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this commerce qualifier entry.
	 *
	 * @param userId the user ID of this commerce qualifier entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this commerce qualifier entry.
	 *
	 * @return the user uuid of this commerce qualifier entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this commerce qualifier entry.
	 *
	 * @param userUuid the user uuid of this commerce qualifier entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this commerce qualifier entry.
	 *
	 * @return the user name of this commerce qualifier entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this commerce qualifier entry.
	 *
	 * @param userName the user name of this commerce qualifier entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this commerce qualifier entry.
	 *
	 * @return the create date of this commerce qualifier entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this commerce qualifier entry.
	 *
	 * @param createDate the create date of this commerce qualifier entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this commerce qualifier entry.
	 *
	 * @return the modified date of this commerce qualifier entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this commerce qualifier entry.
	 *
	 * @param modifiedDate the modified date of this commerce qualifier entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the source class name ID of this commerce qualifier entry.
	 *
	 * @return the source class name ID of this commerce qualifier entry
	 */
	public long getSourceClassNameId();

	/**
	 * Sets the source class name ID of this commerce qualifier entry.
	 *
	 * @param sourceClassNameId the source class name ID of this commerce qualifier entry
	 */
	public void setSourceClassNameId(long sourceClassNameId);

	/**
	 * Returns the source class pk of this commerce qualifier entry.
	 *
	 * @return the source class pk of this commerce qualifier entry
	 */
	public long getSourceClassPK();

	/**
	 * Sets the source class pk of this commerce qualifier entry.
	 *
	 * @param sourceClassPK the source class pk of this commerce qualifier entry
	 */
	public void setSourceClassPK(long sourceClassPK);

	/**
	 * Returns the source commerce qualifier metadata key of this commerce qualifier entry.
	 *
	 * @return the source commerce qualifier metadata key of this commerce qualifier entry
	 */
	@AutoEscape
	public String getSourceCommerceQualifierMetadataKey();

	/**
	 * Sets the source commerce qualifier metadata key of this commerce qualifier entry.
	 *
	 * @param sourceCommerceQualifierMetadataKey the source commerce qualifier metadata key of this commerce qualifier entry
	 */
	public void setSourceCommerceQualifierMetadataKey(
		String sourceCommerceQualifierMetadataKey);

	/**
	 * Returns the target class name ID of this commerce qualifier entry.
	 *
	 * @return the target class name ID of this commerce qualifier entry
	 */
	public long getTargetClassNameId();

	/**
	 * Sets the target class name ID of this commerce qualifier entry.
	 *
	 * @param targetClassNameId the target class name ID of this commerce qualifier entry
	 */
	public void setTargetClassNameId(long targetClassNameId);

	/**
	 * Returns the target class pk of this commerce qualifier entry.
	 *
	 * @return the target class pk of this commerce qualifier entry
	 */
	public long getTargetClassPK();

	/**
	 * Sets the target class pk of this commerce qualifier entry.
	 *
	 * @param targetClassPK the target class pk of this commerce qualifier entry
	 */
	public void setTargetClassPK(long targetClassPK);

	/**
	 * Returns the target commerce qualifier metadata key of this commerce qualifier entry.
	 *
	 * @return the target commerce qualifier metadata key of this commerce qualifier entry
	 */
	@AutoEscape
	public String getTargetCommerceQualifierMetadataKey();

	/**
	 * Sets the target commerce qualifier metadata key of this commerce qualifier entry.
	 *
	 * @param targetCommerceQualifierMetadataKey the target commerce qualifier metadata key of this commerce qualifier entry
	 */
	public void setTargetCommerceQualifierMetadataKey(
		String targetCommerceQualifierMetadataKey);

	@Override
	public CommerceQualifierEntry cloneWithOriginalValues();

}