/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.notifications.admin.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.notifications.admin.model.NotificationsQueueEntry;
import com.liferay.notifications.admin.model.NotificationsQueueEntryModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the NotificationsQueueEntry service. Represents a row in the &quot;NotificationsQueueEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>NotificationsQueueEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NotificationsQueueEntryImpl}.
 * </p>
 *
 * @author Gabriel Albuquerque
 * @see NotificationsQueueEntryImpl
 * @generated
 */
@JSON(strict = true)
public class NotificationsQueueEntryModelImpl
	extends BaseModelImpl<NotificationsQueueEntry>
	implements NotificationsQueueEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a notifications queue entry model instance should use the <code>NotificationsQueueEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "NotificationsQueueEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT},
		{"notificationsQueueEntryId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"classNameId", Types.BIGINT},
		{"classPK", Types.BIGINT}, {"notificationsTemplateId", Types.BIGINT},
		{"from_", Types.VARCHAR}, {"fromName", Types.VARCHAR},
		{"to_", Types.VARCHAR}, {"toName", Types.VARCHAR},
		{"cc", Types.VARCHAR}, {"bcc", Types.VARCHAR},
		{"subject", Types.VARCHAR}, {"body", Types.VARCHAR},
		{"priority", Types.DOUBLE}, {"sent", Types.BOOLEAN},
		{"sentDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("notificationsQueueEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("notificationsTemplateId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("from_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fromName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("to_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("toName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("cc", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("bcc", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("subject", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("body", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("priority", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("sent", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("sentDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table NotificationsQueueEntry (mvccVersion LONG default 0 not null,notificationsQueueEntryId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,classNameId LONG,classPK LONG,notificationsTemplateId LONG,from_ VARCHAR(75) null,fromName VARCHAR(75) null,to_ VARCHAR(75) null,toName VARCHAR(75) null,cc VARCHAR(75) null,bcc VARCHAR(75) null,subject VARCHAR(75) null,body VARCHAR(75) null,priority DOUBLE,sent BOOLEAN,sentDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table NotificationsQueueEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY notificationsQueueEntry.priority DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY NotificationsQueueEntry.priority DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLASSNAMEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLASSPK_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NOTIFICATIONSTEMPLATEID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SENT_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SENTDATE_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PRIORITY_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public NotificationsQueueEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _notificationsQueueEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setNotificationsQueueEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _notificationsQueueEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return NotificationsQueueEntry.class;
	}

	@Override
	public String getModelClassName() {
		return NotificationsQueueEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<NotificationsQueueEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<NotificationsQueueEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NotificationsQueueEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((NotificationsQueueEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<NotificationsQueueEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<NotificationsQueueEntry, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(NotificationsQueueEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<NotificationsQueueEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<NotificationsQueueEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<NotificationsQueueEntry, Object>>
		_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<NotificationsQueueEntry, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<NotificationsQueueEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<NotificationsQueueEntry, Object>>();
		Map<String, BiConsumer<NotificationsQueueEntry, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<NotificationsQueueEntry, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", NotificationsQueueEntry::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<NotificationsQueueEntry, Long>)
				NotificationsQueueEntry::setMvccVersion);
		attributeGetterFunctions.put(
			"notificationsQueueEntryId",
			NotificationsQueueEntry::getNotificationsQueueEntryId);
		attributeSetterBiConsumers.put(
			"notificationsQueueEntryId",
			(BiConsumer<NotificationsQueueEntry, Long>)
				NotificationsQueueEntry::setNotificationsQueueEntryId);
		attributeGetterFunctions.put(
			"groupId", NotificationsQueueEntry::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<NotificationsQueueEntry, Long>)
				NotificationsQueueEntry::setGroupId);
		attributeGetterFunctions.put(
			"companyId", NotificationsQueueEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<NotificationsQueueEntry, Long>)
				NotificationsQueueEntry::setCompanyId);
		attributeGetterFunctions.put(
			"userId", NotificationsQueueEntry::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<NotificationsQueueEntry, Long>)
				NotificationsQueueEntry::setUserId);
		attributeGetterFunctions.put(
			"userName", NotificationsQueueEntry::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<NotificationsQueueEntry, String>)
				NotificationsQueueEntry::setUserName);
		attributeGetterFunctions.put(
			"createDate", NotificationsQueueEntry::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<NotificationsQueueEntry, Date>)
				NotificationsQueueEntry::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", NotificationsQueueEntry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<NotificationsQueueEntry, Date>)
				NotificationsQueueEntry::setModifiedDate);
		attributeGetterFunctions.put(
			"classNameId", NotificationsQueueEntry::getClassNameId);
		attributeSetterBiConsumers.put(
			"classNameId",
			(BiConsumer<NotificationsQueueEntry, Long>)
				NotificationsQueueEntry::setClassNameId);
		attributeGetterFunctions.put(
			"classPK", NotificationsQueueEntry::getClassPK);
		attributeSetterBiConsumers.put(
			"classPK",
			(BiConsumer<NotificationsQueueEntry, Long>)
				NotificationsQueueEntry::setClassPK);
		attributeGetterFunctions.put(
			"notificationsTemplateId",
			NotificationsQueueEntry::getNotificationsTemplateId);
		attributeSetterBiConsumers.put(
			"notificationsTemplateId",
			(BiConsumer<NotificationsQueueEntry, Long>)
				NotificationsQueueEntry::setNotificationsTemplateId);
		attributeGetterFunctions.put("from", NotificationsQueueEntry::getFrom);
		attributeSetterBiConsumers.put(
			"from",
			(BiConsumer<NotificationsQueueEntry, String>)
				NotificationsQueueEntry::setFrom);
		attributeGetterFunctions.put(
			"fromName", NotificationsQueueEntry::getFromName);
		attributeSetterBiConsumers.put(
			"fromName",
			(BiConsumer<NotificationsQueueEntry, String>)
				NotificationsQueueEntry::setFromName);
		attributeGetterFunctions.put("to", NotificationsQueueEntry::getTo);
		attributeSetterBiConsumers.put(
			"to",
			(BiConsumer<NotificationsQueueEntry, String>)
				NotificationsQueueEntry::setTo);
		attributeGetterFunctions.put(
			"toName", NotificationsQueueEntry::getToName);
		attributeSetterBiConsumers.put(
			"toName",
			(BiConsumer<NotificationsQueueEntry, String>)
				NotificationsQueueEntry::setToName);
		attributeGetterFunctions.put("cc", NotificationsQueueEntry::getCc);
		attributeSetterBiConsumers.put(
			"cc",
			(BiConsumer<NotificationsQueueEntry, String>)
				NotificationsQueueEntry::setCc);
		attributeGetterFunctions.put("bcc", NotificationsQueueEntry::getBcc);
		attributeSetterBiConsumers.put(
			"bcc",
			(BiConsumer<NotificationsQueueEntry, String>)
				NotificationsQueueEntry::setBcc);
		attributeGetterFunctions.put(
			"subject", NotificationsQueueEntry::getSubject);
		attributeSetterBiConsumers.put(
			"subject",
			(BiConsumer<NotificationsQueueEntry, String>)
				NotificationsQueueEntry::setSubject);
		attributeGetterFunctions.put("body", NotificationsQueueEntry::getBody);
		attributeSetterBiConsumers.put(
			"body",
			(BiConsumer<NotificationsQueueEntry, String>)
				NotificationsQueueEntry::setBody);
		attributeGetterFunctions.put(
			"priority", NotificationsQueueEntry::getPriority);
		attributeSetterBiConsumers.put(
			"priority",
			(BiConsumer<NotificationsQueueEntry, Double>)
				NotificationsQueueEntry::setPriority);
		attributeGetterFunctions.put("sent", NotificationsQueueEntry::getSent);
		attributeSetterBiConsumers.put(
			"sent",
			(BiConsumer<NotificationsQueueEntry, Boolean>)
				NotificationsQueueEntry::setSent);
		attributeGetterFunctions.put(
			"sentDate", NotificationsQueueEntry::getSentDate);
		attributeSetterBiConsumers.put(
			"sentDate",
			(BiConsumer<NotificationsQueueEntry, Date>)
				NotificationsQueueEntry::setSentDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getNotificationsQueueEntryId() {
		return _notificationsQueueEntryId;
	}

	@Override
	public void setNotificationsQueueEntryId(long notificationsQueueEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_notificationsQueueEntryId = notificationsQueueEntryId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@JSON
	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classNameId = classNameId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalClassNameId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("classNameId"));
	}

	@JSON
	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classPK = classPK;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalClassPK() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("classPK"));
	}

	@JSON
	@Override
	public long getNotificationsTemplateId() {
		return _notificationsTemplateId;
	}

	@Override
	public void setNotificationsTemplateId(long notificationsTemplateId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_notificationsTemplateId = notificationsTemplateId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalNotificationsTemplateId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("notificationsTemplateId"));
	}

	@JSON
	@Override
	public String getFrom() {
		if (_from == null) {
			return "";
		}
		else {
			return _from;
		}
	}

	@Override
	public void setFrom(String from) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_from = from;
	}

	@JSON
	@Override
	public String getFromName() {
		if (_fromName == null) {
			return "";
		}
		else {
			return _fromName;
		}
	}

	@Override
	public void setFromName(String fromName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fromName = fromName;
	}

	@JSON
	@Override
	public String getTo() {
		if (_to == null) {
			return "";
		}
		else {
			return _to;
		}
	}

	@Override
	public void setTo(String to) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_to = to;
	}

	@JSON
	@Override
	public String getToName() {
		if (_toName == null) {
			return "";
		}
		else {
			return _toName;
		}
	}

	@Override
	public void setToName(String toName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_toName = toName;
	}

	@JSON
	@Override
	public String getCc() {
		if (_cc == null) {
			return "";
		}
		else {
			return _cc;
		}
	}

	@Override
	public void setCc(String cc) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cc = cc;
	}

	@JSON
	@Override
	public String getBcc() {
		if (_bcc == null) {
			return "";
		}
		else {
			return _bcc;
		}
	}

	@Override
	public void setBcc(String bcc) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bcc = bcc;
	}

	@JSON
	@Override
	public String getSubject() {
		if (_subject == null) {
			return "";
		}
		else {
			return _subject;
		}
	}

	@Override
	public void setSubject(String subject) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subject = subject;
	}

	@JSON
	@Override
	public String getBody() {
		if (_body == null) {
			return "";
		}
		else {
			return _body;
		}
	}

	@Override
	public void setBody(String body) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_body = body;
	}

	@JSON
	@Override
	public double getPriority() {
		return _priority;
	}

	@Override
	public void setPriority(double priority) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_priority = priority;
	}

	@JSON
	@Override
	public boolean getSent() {
		return _sent;
	}

	@JSON
	@Override
	public boolean isSent() {
		return _sent;
	}

	@Override
	public void setSent(boolean sent) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sent = sent;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalSent() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("sent"));
	}

	@JSON
	@Override
	public Date getSentDate() {
		return _sentDate;
	}

	@Override
	public void setSentDate(Date sentDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sentDate = sentDate;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalSentDate() {
		return getColumnOriginalValue("sentDate");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), NotificationsQueueEntry.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public NotificationsQueueEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, NotificationsQueueEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NotificationsQueueEntryImpl notificationsQueueEntryImpl =
			new NotificationsQueueEntryImpl();

		notificationsQueueEntryImpl.setMvccVersion(getMvccVersion());
		notificationsQueueEntryImpl.setNotificationsQueueEntryId(
			getNotificationsQueueEntryId());
		notificationsQueueEntryImpl.setGroupId(getGroupId());
		notificationsQueueEntryImpl.setCompanyId(getCompanyId());
		notificationsQueueEntryImpl.setUserId(getUserId());
		notificationsQueueEntryImpl.setUserName(getUserName());
		notificationsQueueEntryImpl.setCreateDate(getCreateDate());
		notificationsQueueEntryImpl.setModifiedDate(getModifiedDate());
		notificationsQueueEntryImpl.setClassNameId(getClassNameId());
		notificationsQueueEntryImpl.setClassPK(getClassPK());
		notificationsQueueEntryImpl.setNotificationsTemplateId(
			getNotificationsTemplateId());
		notificationsQueueEntryImpl.setFrom(getFrom());
		notificationsQueueEntryImpl.setFromName(getFromName());
		notificationsQueueEntryImpl.setTo(getTo());
		notificationsQueueEntryImpl.setToName(getToName());
		notificationsQueueEntryImpl.setCc(getCc());
		notificationsQueueEntryImpl.setBcc(getBcc());
		notificationsQueueEntryImpl.setSubject(getSubject());
		notificationsQueueEntryImpl.setBody(getBody());
		notificationsQueueEntryImpl.setPriority(getPriority());
		notificationsQueueEntryImpl.setSent(isSent());
		notificationsQueueEntryImpl.setSentDate(getSentDate());

		notificationsQueueEntryImpl.resetOriginalValues();

		return notificationsQueueEntryImpl;
	}

	@Override
	public NotificationsQueueEntry cloneWithOriginalValues() {
		NotificationsQueueEntryImpl notificationsQueueEntryImpl =
			new NotificationsQueueEntryImpl();

		notificationsQueueEntryImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		notificationsQueueEntryImpl.setNotificationsQueueEntryId(
			this.<Long>getColumnOriginalValue("notificationsQueueEntryId"));
		notificationsQueueEntryImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		notificationsQueueEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		notificationsQueueEntryImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		notificationsQueueEntryImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		notificationsQueueEntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		notificationsQueueEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		notificationsQueueEntryImpl.setClassNameId(
			this.<Long>getColumnOriginalValue("classNameId"));
		notificationsQueueEntryImpl.setClassPK(
			this.<Long>getColumnOriginalValue("classPK"));
		notificationsQueueEntryImpl.setNotificationsTemplateId(
			this.<Long>getColumnOriginalValue("notificationsTemplateId"));
		notificationsQueueEntryImpl.setFrom(
			this.<String>getColumnOriginalValue("from_"));
		notificationsQueueEntryImpl.setFromName(
			this.<String>getColumnOriginalValue("fromName"));
		notificationsQueueEntryImpl.setTo(
			this.<String>getColumnOriginalValue("to_"));
		notificationsQueueEntryImpl.setToName(
			this.<String>getColumnOriginalValue("toName"));
		notificationsQueueEntryImpl.setCc(
			this.<String>getColumnOriginalValue("cc"));
		notificationsQueueEntryImpl.setBcc(
			this.<String>getColumnOriginalValue("bcc"));
		notificationsQueueEntryImpl.setSubject(
			this.<String>getColumnOriginalValue("subject"));
		notificationsQueueEntryImpl.setBody(
			this.<String>getColumnOriginalValue("body"));
		notificationsQueueEntryImpl.setPriority(
			this.<Double>getColumnOriginalValue("priority"));
		notificationsQueueEntryImpl.setSent(
			this.<Boolean>getColumnOriginalValue("sent"));
		notificationsQueueEntryImpl.setSentDate(
			this.<Date>getColumnOriginalValue("sentDate"));

		return notificationsQueueEntryImpl;
	}

	@Override
	public int compareTo(NotificationsQueueEntry notificationsQueueEntry) {
		int value = 0;

		if (getPriority() < notificationsQueueEntry.getPriority()) {
			value = -1;
		}
		else if (getPriority() > notificationsQueueEntry.getPriority()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof NotificationsQueueEntry)) {
			return false;
		}

		NotificationsQueueEntry notificationsQueueEntry =
			(NotificationsQueueEntry)object;

		long primaryKey = notificationsQueueEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<NotificationsQueueEntry> toCacheModel() {
		NotificationsQueueEntryCacheModel notificationsQueueEntryCacheModel =
			new NotificationsQueueEntryCacheModel();

		notificationsQueueEntryCacheModel.mvccVersion = getMvccVersion();

		notificationsQueueEntryCacheModel.notificationsQueueEntryId =
			getNotificationsQueueEntryId();

		notificationsQueueEntryCacheModel.groupId = getGroupId();

		notificationsQueueEntryCacheModel.companyId = getCompanyId();

		notificationsQueueEntryCacheModel.userId = getUserId();

		notificationsQueueEntryCacheModel.userName = getUserName();

		String userName = notificationsQueueEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			notificationsQueueEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			notificationsQueueEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			notificationsQueueEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			notificationsQueueEntryCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			notificationsQueueEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		notificationsQueueEntryCacheModel.classNameId = getClassNameId();

		notificationsQueueEntryCacheModel.classPK = getClassPK();

		notificationsQueueEntryCacheModel.notificationsTemplateId =
			getNotificationsTemplateId();

		notificationsQueueEntryCacheModel.from = getFrom();

		String from = notificationsQueueEntryCacheModel.from;

		if ((from != null) && (from.length() == 0)) {
			notificationsQueueEntryCacheModel.from = null;
		}

		notificationsQueueEntryCacheModel.fromName = getFromName();

		String fromName = notificationsQueueEntryCacheModel.fromName;

		if ((fromName != null) && (fromName.length() == 0)) {
			notificationsQueueEntryCacheModel.fromName = null;
		}

		notificationsQueueEntryCacheModel.to = getTo();

		String to = notificationsQueueEntryCacheModel.to;

		if ((to != null) && (to.length() == 0)) {
			notificationsQueueEntryCacheModel.to = null;
		}

		notificationsQueueEntryCacheModel.toName = getToName();

		String toName = notificationsQueueEntryCacheModel.toName;

		if ((toName != null) && (toName.length() == 0)) {
			notificationsQueueEntryCacheModel.toName = null;
		}

		notificationsQueueEntryCacheModel.cc = getCc();

		String cc = notificationsQueueEntryCacheModel.cc;

		if ((cc != null) && (cc.length() == 0)) {
			notificationsQueueEntryCacheModel.cc = null;
		}

		notificationsQueueEntryCacheModel.bcc = getBcc();

		String bcc = notificationsQueueEntryCacheModel.bcc;

		if ((bcc != null) && (bcc.length() == 0)) {
			notificationsQueueEntryCacheModel.bcc = null;
		}

		notificationsQueueEntryCacheModel.subject = getSubject();

		String subject = notificationsQueueEntryCacheModel.subject;

		if ((subject != null) && (subject.length() == 0)) {
			notificationsQueueEntryCacheModel.subject = null;
		}

		notificationsQueueEntryCacheModel.body = getBody();

		String body = notificationsQueueEntryCacheModel.body;

		if ((body != null) && (body.length() == 0)) {
			notificationsQueueEntryCacheModel.body = null;
		}

		notificationsQueueEntryCacheModel.priority = getPriority();

		notificationsQueueEntryCacheModel.sent = isSent();

		Date sentDate = getSentDate();

		if (sentDate != null) {
			notificationsQueueEntryCacheModel.sentDate = sentDate.getTime();
		}
		else {
			notificationsQueueEntryCacheModel.sentDate = Long.MIN_VALUE;
		}

		return notificationsQueueEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<NotificationsQueueEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<NotificationsQueueEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NotificationsQueueEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(NotificationsQueueEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<NotificationsQueueEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<NotificationsQueueEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NotificationsQueueEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((NotificationsQueueEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, NotificationsQueueEntry>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						NotificationsQueueEntry.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _notificationsQueueEntryId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _classNameId;
	private long _classPK;
	private long _notificationsTemplateId;
	private String _from;
	private String _fromName;
	private String _to;
	private String _toName;
	private String _cc;
	private String _bcc;
	private String _subject;
	private String _body;
	private double _priority;
	private boolean _sent;
	private Date _sentDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<NotificationsQueueEntry, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((NotificationsQueueEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"notificationsQueueEntryId", _notificationsQueueEntryId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("classNameId", _classNameId);
		_columnOriginalValues.put("classPK", _classPK);
		_columnOriginalValues.put(
			"notificationsTemplateId", _notificationsTemplateId);
		_columnOriginalValues.put("from_", _from);
		_columnOriginalValues.put("fromName", _fromName);
		_columnOriginalValues.put("to_", _to);
		_columnOriginalValues.put("toName", _toName);
		_columnOriginalValues.put("cc", _cc);
		_columnOriginalValues.put("bcc", _bcc);
		_columnOriginalValues.put("subject", _subject);
		_columnOriginalValues.put("body", _body);
		_columnOriginalValues.put("priority", _priority);
		_columnOriginalValues.put("sent", _sent);
		_columnOriginalValues.put("sentDate", _sentDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("from_", "from");
		attributeNames.put("to_", "to");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("notificationsQueueEntryId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("classNameId", 256L);

		columnBitmasks.put("classPK", 512L);

		columnBitmasks.put("notificationsTemplateId", 1024L);

		columnBitmasks.put("from_", 2048L);

		columnBitmasks.put("fromName", 4096L);

		columnBitmasks.put("to_", 8192L);

		columnBitmasks.put("toName", 16384L);

		columnBitmasks.put("cc", 32768L);

		columnBitmasks.put("bcc", 65536L);

		columnBitmasks.put("subject", 131072L);

		columnBitmasks.put("body", 262144L);

		columnBitmasks.put("priority", 524288L);

		columnBitmasks.put("sent", 1048576L);

		columnBitmasks.put("sentDate", 2097152L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private NotificationsQueueEntry _escapedModel;

}