/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.product.service.base;

import com.liferay.commerce.product.model.CommerceChannelAccountEntryRel;
import com.liferay.commerce.product.service.CommerceChannelAccountEntryRelService;
import com.liferay.commerce.product.service.CommerceChannelAccountEntryRelServiceUtil;
import com.liferay.commerce.product.service.persistence.CommerceChannelAccountEntryRelPersistence;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.lang.reflect.Field;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the commerce channel account entry rel remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.commerce.product.service.impl.CommerceChannelAccountEntryRelServiceImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see com.liferay.commerce.product.service.impl.CommerceChannelAccountEntryRelServiceImpl
 * @generated
 */
public abstract class CommerceChannelAccountEntryRelServiceBaseImpl
	extends BaseServiceImpl
	implements CommerceChannelAccountEntryRelService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CommerceChannelAccountEntryRelService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>CommerceChannelAccountEntryRelServiceUtil</code>.
	 */

	/**
	 * Returns the commerce channel account entry rel local service.
	 *
	 * @return the commerce channel account entry rel local service
	 */
	public com.liferay.commerce.product.service.
		CommerceChannelAccountEntryRelLocalService
			getCommerceChannelAccountEntryRelLocalService() {

		return commerceChannelAccountEntryRelLocalService;
	}

	/**
	 * Sets the commerce channel account entry rel local service.
	 *
	 * @param commerceChannelAccountEntryRelLocalService the commerce channel account entry rel local service
	 */
	public void setCommerceChannelAccountEntryRelLocalService(
		com.liferay.commerce.product.service.
			CommerceChannelAccountEntryRelLocalService
				commerceChannelAccountEntryRelLocalService) {

		this.commerceChannelAccountEntryRelLocalService =
			commerceChannelAccountEntryRelLocalService;
	}

	/**
	 * Returns the commerce channel account entry rel remote service.
	 *
	 * @return the commerce channel account entry rel remote service
	 */
	public CommerceChannelAccountEntryRelService
		getCommerceChannelAccountEntryRelService() {

		return commerceChannelAccountEntryRelService;
	}

	/**
	 * Sets the commerce channel account entry rel remote service.
	 *
	 * @param commerceChannelAccountEntryRelService the commerce channel account entry rel remote service
	 */
	public void setCommerceChannelAccountEntryRelService(
		CommerceChannelAccountEntryRelService
			commerceChannelAccountEntryRelService) {

		this.commerceChannelAccountEntryRelService =
			commerceChannelAccountEntryRelService;
	}

	/**
	 * Returns the commerce channel account entry rel persistence.
	 *
	 * @return the commerce channel account entry rel persistence
	 */
	public CommerceChannelAccountEntryRelPersistence
		getCommerceChannelAccountEntryRelPersistence() {

		return commerceChannelAccountEntryRelPersistence;
	}

	/**
	 * Sets the commerce channel account entry rel persistence.
	 *
	 * @param commerceChannelAccountEntryRelPersistence the commerce channel account entry rel persistence
	 */
	public void setCommerceChannelAccountEntryRelPersistence(
		CommerceChannelAccountEntryRelPersistence
			commerceChannelAccountEntryRelPersistence) {

		this.commerceChannelAccountEntryRelPersistence =
			commerceChannelAccountEntryRelPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		_setServiceUtilService(commerceChannelAccountEntryRelService);
	}

	public void destroy() {
		_setServiceUtilService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CommerceChannelAccountEntryRelService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CommerceChannelAccountEntryRel.class;
	}

	protected String getModelClassName() {
		return CommerceChannelAccountEntryRel.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				commerceChannelAccountEntryRelPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		CommerceChannelAccountEntryRelService
			commerceChannelAccountEntryRelService) {

		try {
			Field field =
				CommerceChannelAccountEntryRelServiceUtil.class.
					getDeclaredField("_service");

			field.setAccessible(true);

			field.set(null, commerceChannelAccountEntryRelService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@BeanReference(
		type = com.liferay.commerce.product.service.CommerceChannelAccountEntryRelLocalService.class
	)
	protected com.liferay.commerce.product.service.
		CommerceChannelAccountEntryRelLocalService
			commerceChannelAccountEntryRelLocalService;

	@BeanReference(type = CommerceChannelAccountEntryRelService.class)
	protected CommerceChannelAccountEntryRelService
		commerceChannelAccountEntryRelService;

	@BeanReference(type = CommerceChannelAccountEntryRelPersistence.class)
	protected CommerceChannelAccountEntryRelPersistence
		commerceChannelAccountEntryRelPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

}