/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.product.service.base;

import com.liferay.commerce.product.model.CPInstanceOptionValueRel;
import com.liferay.commerce.product.service.CPInstanceOptionValueRelService;
import com.liferay.commerce.product.service.CPInstanceOptionValueRelServiceUtil;
import com.liferay.commerce.product.service.persistence.CPInstanceOptionValueRelFinder;
import com.liferay.commerce.product.service.persistence.CPInstanceOptionValueRelPersistence;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.lang.reflect.Field;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the cp instance option value rel remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.commerce.product.service.impl.CPInstanceOptionValueRelServiceImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see com.liferay.commerce.product.service.impl.CPInstanceOptionValueRelServiceImpl
 * @generated
 */
public abstract class CPInstanceOptionValueRelServiceBaseImpl
	extends BaseServiceImpl
	implements CPInstanceOptionValueRelService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CPInstanceOptionValueRelService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>CPInstanceOptionValueRelServiceUtil</code>.
	 */

	/**
	 * Returns the cp instance option value rel local service.
	 *
	 * @return the cp instance option value rel local service
	 */
	public
		com.liferay.commerce.product.service.
			CPInstanceOptionValueRelLocalService
				getCPInstanceOptionValueRelLocalService() {

		return cpInstanceOptionValueRelLocalService;
	}

	/**
	 * Sets the cp instance option value rel local service.
	 *
	 * @param cpInstanceOptionValueRelLocalService the cp instance option value rel local service
	 */
	public void setCPInstanceOptionValueRelLocalService(
		com.liferay.commerce.product.service.
			CPInstanceOptionValueRelLocalService
				cpInstanceOptionValueRelLocalService) {

		this.cpInstanceOptionValueRelLocalService =
			cpInstanceOptionValueRelLocalService;
	}

	/**
	 * Returns the cp instance option value rel remote service.
	 *
	 * @return the cp instance option value rel remote service
	 */
	public CPInstanceOptionValueRelService
		getCPInstanceOptionValueRelService() {

		return cpInstanceOptionValueRelService;
	}

	/**
	 * Sets the cp instance option value rel remote service.
	 *
	 * @param cpInstanceOptionValueRelService the cp instance option value rel remote service
	 */
	public void setCPInstanceOptionValueRelService(
		CPInstanceOptionValueRelService cpInstanceOptionValueRelService) {

		this.cpInstanceOptionValueRelService = cpInstanceOptionValueRelService;
	}

	/**
	 * Returns the cp instance option value rel persistence.
	 *
	 * @return the cp instance option value rel persistence
	 */
	public CPInstanceOptionValueRelPersistence
		getCPInstanceOptionValueRelPersistence() {

		return cpInstanceOptionValueRelPersistence;
	}

	/**
	 * Sets the cp instance option value rel persistence.
	 *
	 * @param cpInstanceOptionValueRelPersistence the cp instance option value rel persistence
	 */
	public void setCPInstanceOptionValueRelPersistence(
		CPInstanceOptionValueRelPersistence
			cpInstanceOptionValueRelPersistence) {

		this.cpInstanceOptionValueRelPersistence =
			cpInstanceOptionValueRelPersistence;
	}

	/**
	 * Returns the cp instance option value rel finder.
	 *
	 * @return the cp instance option value rel finder
	 */
	public CPInstanceOptionValueRelFinder getCPInstanceOptionValueRelFinder() {
		return cpInstanceOptionValueRelFinder;
	}

	/**
	 * Sets the cp instance option value rel finder.
	 *
	 * @param cpInstanceOptionValueRelFinder the cp instance option value rel finder
	 */
	public void setCPInstanceOptionValueRelFinder(
		CPInstanceOptionValueRelFinder cpInstanceOptionValueRelFinder) {

		this.cpInstanceOptionValueRelFinder = cpInstanceOptionValueRelFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		_setServiceUtilService(cpInstanceOptionValueRelService);
	}

	public void destroy() {
		_setServiceUtilService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CPInstanceOptionValueRelService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CPInstanceOptionValueRel.class;
	}

	protected String getModelClassName() {
		return CPInstanceOptionValueRel.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				cpInstanceOptionValueRelPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		CPInstanceOptionValueRelService cpInstanceOptionValueRelService) {

		try {
			Field field =
				CPInstanceOptionValueRelServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, cpInstanceOptionValueRelService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@BeanReference(
		type = com.liferay.commerce.product.service.CPInstanceOptionValueRelLocalService.class
	)
	protected
		com.liferay.commerce.product.service.
			CPInstanceOptionValueRelLocalService
				cpInstanceOptionValueRelLocalService;

	@BeanReference(type = CPInstanceOptionValueRelService.class)
	protected CPInstanceOptionValueRelService cpInstanceOptionValueRelService;

	@BeanReference(type = CPInstanceOptionValueRelPersistence.class)
	protected CPInstanceOptionValueRelPersistence
		cpInstanceOptionValueRelPersistence;

	@BeanReference(type = CPInstanceOptionValueRelFinder.class)
	protected CPInstanceOptionValueRelFinder cpInstanceOptionValueRelFinder;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

}