create table NotificationQueueEntry (
	mvccVersion LONG default 0 not null,
	notificationQueueEntryId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	classNameId LONG,
	classPK LONG,
	notificationTemplateId LONG,
	from_ VARCHAR(75) null,
	fromName VARCHAR(75) null,
	to_ VARCHAR(75) null,
	toName VARCHAR(75) null,
	cc VARCHAR(75) null,
	bcc VARCHAR(75) null,
	subject VARCHAR(75) null,
	body VARCHAR(75) null,
	priority DOUBLE,
	sent BOOLEAN,
	sentDate DATE null
);

create table NotificationTemplate (
	mvccVersion LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	notificationTemplateId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	name STRING null,
	description VARCHAR(75) null,
	from_ VARCHAR(75) null,
	fromName STRING null,
	to_ VARCHAR(75) null,
	cc VARCHAR(75) null,
	bcc VARCHAR(75) null,
	enabled BOOLEAN,
	subject STRING null,
	body STRING null
);