info:
    description:
        "A Java client JAR is available for use with the group ID 'com.liferay', artifact ID
        'com.liferay.frontend.view.state.rest.client', and version '1.0.0'."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Frontend View State"
    version: v1.0
openapi: 3.0.1
paths:
    "/active-view/{activeViewId}/page-layout/{pageLayoutId}/portlet/{portletId}":
        get:
            parameters:
                - in: path
                  name: activeViewId
                  required: true
                  schema:
                      type: string
                - in: path
                  name: pageLayoutId
                  schema:
                      format: int64
                      type: integer
                - in: path
                  name: portletId
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                type: object
                        application/xml:
                            schema:
                                type: object
            tags: ["ActiveView"]
        put:
            parameters:
                - in: path
                  name: activeViewId
                  required: true
                  schema:
                      type: string
                - in: path
                  name: pageLayoutId
                  schema:
                      format: int64
                      type: integer
                - in: path
                  name: portletId
                  schema:
                      type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            type: string
                    application/xml:
                        schema:
                            type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                type: object
                        application/xml:
                            schema:
                                type: object
            tags: ["ActiveView"]