/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.discount.service.base;

import com.liferay.commerce.discount.model.CommerceDiscountOrderTypeRel;
import com.liferay.commerce.discount.service.CommerceDiscountOrderTypeRelService;
import com.liferay.commerce.discount.service.CommerceDiscountOrderTypeRelServiceUtil;
import com.liferay.commerce.discount.service.persistence.CommerceDiscountOrderTypeRelPersistence;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.lang.reflect.Field;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the commerce discount order type rel remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.commerce.discount.service.impl.CommerceDiscountOrderTypeRelServiceImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see com.liferay.commerce.discount.service.impl.CommerceDiscountOrderTypeRelServiceImpl
 * @generated
 */
public abstract class CommerceDiscountOrderTypeRelServiceBaseImpl
	extends BaseServiceImpl
	implements CommerceDiscountOrderTypeRelService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CommerceDiscountOrderTypeRelService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>CommerceDiscountOrderTypeRelServiceUtil</code>.
	 */

	/**
	 * Returns the commerce discount order type rel local service.
	 *
	 * @return the commerce discount order type rel local service
	 */
	public com.liferay.commerce.discount.service.
		CommerceDiscountOrderTypeRelLocalService
			getCommerceDiscountOrderTypeRelLocalService() {

		return commerceDiscountOrderTypeRelLocalService;
	}

	/**
	 * Sets the commerce discount order type rel local service.
	 *
	 * @param commerceDiscountOrderTypeRelLocalService the commerce discount order type rel local service
	 */
	public void setCommerceDiscountOrderTypeRelLocalService(
		com.liferay.commerce.discount.service.
			CommerceDiscountOrderTypeRelLocalService
				commerceDiscountOrderTypeRelLocalService) {

		this.commerceDiscountOrderTypeRelLocalService =
			commerceDiscountOrderTypeRelLocalService;
	}

	/**
	 * Returns the commerce discount order type rel remote service.
	 *
	 * @return the commerce discount order type rel remote service
	 */
	public CommerceDiscountOrderTypeRelService
		getCommerceDiscountOrderTypeRelService() {

		return commerceDiscountOrderTypeRelService;
	}

	/**
	 * Sets the commerce discount order type rel remote service.
	 *
	 * @param commerceDiscountOrderTypeRelService the commerce discount order type rel remote service
	 */
	public void setCommerceDiscountOrderTypeRelService(
		CommerceDiscountOrderTypeRelService
			commerceDiscountOrderTypeRelService) {

		this.commerceDiscountOrderTypeRelService =
			commerceDiscountOrderTypeRelService;
	}

	/**
	 * Returns the commerce discount order type rel persistence.
	 *
	 * @return the commerce discount order type rel persistence
	 */
	public CommerceDiscountOrderTypeRelPersistence
		getCommerceDiscountOrderTypeRelPersistence() {

		return commerceDiscountOrderTypeRelPersistence;
	}

	/**
	 * Sets the commerce discount order type rel persistence.
	 *
	 * @param commerceDiscountOrderTypeRelPersistence the commerce discount order type rel persistence
	 */
	public void setCommerceDiscountOrderTypeRelPersistence(
		CommerceDiscountOrderTypeRelPersistence
			commerceDiscountOrderTypeRelPersistence) {

		this.commerceDiscountOrderTypeRelPersistence =
			commerceDiscountOrderTypeRelPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		_setServiceUtilService(commerceDiscountOrderTypeRelService);
	}

	public void destroy() {
		_setServiceUtilService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CommerceDiscountOrderTypeRelService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CommerceDiscountOrderTypeRel.class;
	}

	protected String getModelClassName() {
		return CommerceDiscountOrderTypeRel.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				commerceDiscountOrderTypeRelPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		CommerceDiscountOrderTypeRelService
			commerceDiscountOrderTypeRelService) {

		try {
			Field field =
				CommerceDiscountOrderTypeRelServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, commerceDiscountOrderTypeRelService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@BeanReference(
		type = com.liferay.commerce.discount.service.CommerceDiscountOrderTypeRelLocalService.class
	)
	protected com.liferay.commerce.discount.service.
		CommerceDiscountOrderTypeRelLocalService
			commerceDiscountOrderTypeRelLocalService;

	@BeanReference(type = CommerceDiscountOrderTypeRelService.class)
	protected CommerceDiscountOrderTypeRelService
		commerceDiscountOrderTypeRelService;

	@BeanReference(type = CommerceDiscountOrderTypeRelPersistence.class)
	protected CommerceDiscountOrderTypeRelPersistence
		commerceDiscountOrderTypeRelPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

}