/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.discount.service.base;

import com.liferay.commerce.discount.model.CommerceDiscountAccountRel;
import com.liferay.commerce.discount.service.CommerceDiscountAccountRelService;
import com.liferay.commerce.discount.service.CommerceDiscountAccountRelServiceUtil;
import com.liferay.commerce.discount.service.persistence.CommerceDiscountAccountRelFinder;
import com.liferay.commerce.discount.service.persistence.CommerceDiscountAccountRelPersistence;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.lang.reflect.Field;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the commerce discount account rel remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.commerce.discount.service.impl.CommerceDiscountAccountRelServiceImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see com.liferay.commerce.discount.service.impl.CommerceDiscountAccountRelServiceImpl
 * @generated
 */
public abstract class CommerceDiscountAccountRelServiceBaseImpl
	extends BaseServiceImpl
	implements CommerceDiscountAccountRelService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CommerceDiscountAccountRelService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>CommerceDiscountAccountRelServiceUtil</code>.
	 */

	/**
	 * Returns the commerce discount account rel local service.
	 *
	 * @return the commerce discount account rel local service
	 */
	public
		com.liferay.commerce.discount.service.
			CommerceDiscountAccountRelLocalService
				getCommerceDiscountAccountRelLocalService() {

		return commerceDiscountAccountRelLocalService;
	}

	/**
	 * Sets the commerce discount account rel local service.
	 *
	 * @param commerceDiscountAccountRelLocalService the commerce discount account rel local service
	 */
	public void setCommerceDiscountAccountRelLocalService(
		com.liferay.commerce.discount.service.
			CommerceDiscountAccountRelLocalService
				commerceDiscountAccountRelLocalService) {

		this.commerceDiscountAccountRelLocalService =
			commerceDiscountAccountRelLocalService;
	}

	/**
	 * Returns the commerce discount account rel remote service.
	 *
	 * @return the commerce discount account rel remote service
	 */
	public CommerceDiscountAccountRelService
		getCommerceDiscountAccountRelService() {

		return commerceDiscountAccountRelService;
	}

	/**
	 * Sets the commerce discount account rel remote service.
	 *
	 * @param commerceDiscountAccountRelService the commerce discount account rel remote service
	 */
	public void setCommerceDiscountAccountRelService(
		CommerceDiscountAccountRelService commerceDiscountAccountRelService) {

		this.commerceDiscountAccountRelService =
			commerceDiscountAccountRelService;
	}

	/**
	 * Returns the commerce discount account rel persistence.
	 *
	 * @return the commerce discount account rel persistence
	 */
	public CommerceDiscountAccountRelPersistence
		getCommerceDiscountAccountRelPersistence() {

		return commerceDiscountAccountRelPersistence;
	}

	/**
	 * Sets the commerce discount account rel persistence.
	 *
	 * @param commerceDiscountAccountRelPersistence the commerce discount account rel persistence
	 */
	public void setCommerceDiscountAccountRelPersistence(
		CommerceDiscountAccountRelPersistence
			commerceDiscountAccountRelPersistence) {

		this.commerceDiscountAccountRelPersistence =
			commerceDiscountAccountRelPersistence;
	}

	/**
	 * Returns the commerce discount account rel finder.
	 *
	 * @return the commerce discount account rel finder
	 */
	public CommerceDiscountAccountRelFinder
		getCommerceDiscountAccountRelFinder() {

		return commerceDiscountAccountRelFinder;
	}

	/**
	 * Sets the commerce discount account rel finder.
	 *
	 * @param commerceDiscountAccountRelFinder the commerce discount account rel finder
	 */
	public void setCommerceDiscountAccountRelFinder(
		CommerceDiscountAccountRelFinder commerceDiscountAccountRelFinder) {

		this.commerceDiscountAccountRelFinder =
			commerceDiscountAccountRelFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		_setServiceUtilService(commerceDiscountAccountRelService);
	}

	public void destroy() {
		_setServiceUtilService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CommerceDiscountAccountRelService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CommerceDiscountAccountRel.class;
	}

	protected String getModelClassName() {
		return CommerceDiscountAccountRel.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				commerceDiscountAccountRelPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		CommerceDiscountAccountRelService commerceDiscountAccountRelService) {

		try {
			Field field =
				CommerceDiscountAccountRelServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, commerceDiscountAccountRelService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@BeanReference(
		type = com.liferay.commerce.discount.service.CommerceDiscountAccountRelLocalService.class
	)
	protected
		com.liferay.commerce.discount.service.
			CommerceDiscountAccountRelLocalService
				commerceDiscountAccountRelLocalService;

	@BeanReference(type = CommerceDiscountAccountRelService.class)
	protected CommerceDiscountAccountRelService
		commerceDiscountAccountRelService;

	@BeanReference(type = CommerceDiscountAccountRelPersistence.class)
	protected CommerceDiscountAccountRelPersistence
		commerceDiscountAccountRelPersistence;

	@BeanReference(type = CommerceDiscountAccountRelFinder.class)
	protected CommerceDiscountAccountRelFinder commerceDiscountAccountRelFinder;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

}