/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.payment.service.base;

import com.liferay.commerce.payment.model.CommercePaymentMethodGroupRelQualifier;
import com.liferay.commerce.payment.service.CommercePaymentMethodGroupRelQualifierService;
import com.liferay.commerce.payment.service.CommercePaymentMethodGroupRelQualifierServiceUtil;
import com.liferay.commerce.payment.service.persistence.CommercePaymentMethodGroupRelQualifierPersistence;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.lang.reflect.Field;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the commerce payment method group rel qualifier remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.commerce.payment.service.impl.CommercePaymentMethodGroupRelQualifierServiceImpl}.
 * </p>
 *
 * @author Luca Pellizzon
 * @see com.liferay.commerce.payment.service.impl.CommercePaymentMethodGroupRelQualifierServiceImpl
 * @generated
 */
public abstract class CommercePaymentMethodGroupRelQualifierServiceBaseImpl
	extends BaseServiceImpl
	implements CommercePaymentMethodGroupRelQualifierService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CommercePaymentMethodGroupRelQualifierService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>CommercePaymentMethodGroupRelQualifierServiceUtil</code>.
	 */

	/**
	 * Returns the commerce payment method group rel qualifier local service.
	 *
	 * @return the commerce payment method group rel qualifier local service
	 */
	public com.liferay.commerce.payment.service.
		CommercePaymentMethodGroupRelQualifierLocalService
			getCommercePaymentMethodGroupRelQualifierLocalService() {

		return commercePaymentMethodGroupRelQualifierLocalService;
	}

	/**
	 * Sets the commerce payment method group rel qualifier local service.
	 *
	 * @param commercePaymentMethodGroupRelQualifierLocalService the commerce payment method group rel qualifier local service
	 */
	public void setCommercePaymentMethodGroupRelQualifierLocalService(
		com.liferay.commerce.payment.service.
			CommercePaymentMethodGroupRelQualifierLocalService
				commercePaymentMethodGroupRelQualifierLocalService) {

		this.commercePaymentMethodGroupRelQualifierLocalService =
			commercePaymentMethodGroupRelQualifierLocalService;
	}

	/**
	 * Returns the commerce payment method group rel qualifier remote service.
	 *
	 * @return the commerce payment method group rel qualifier remote service
	 */
	public CommercePaymentMethodGroupRelQualifierService
		getCommercePaymentMethodGroupRelQualifierService() {

		return commercePaymentMethodGroupRelQualifierService;
	}

	/**
	 * Sets the commerce payment method group rel qualifier remote service.
	 *
	 * @param commercePaymentMethodGroupRelQualifierService the commerce payment method group rel qualifier remote service
	 */
	public void setCommercePaymentMethodGroupRelQualifierService(
		CommercePaymentMethodGroupRelQualifierService
			commercePaymentMethodGroupRelQualifierService) {

		this.commercePaymentMethodGroupRelQualifierService =
			commercePaymentMethodGroupRelQualifierService;
	}

	/**
	 * Returns the commerce payment method group rel qualifier persistence.
	 *
	 * @return the commerce payment method group rel qualifier persistence
	 */
	public CommercePaymentMethodGroupRelQualifierPersistence
		getCommercePaymentMethodGroupRelQualifierPersistence() {

		return commercePaymentMethodGroupRelQualifierPersistence;
	}

	/**
	 * Sets the commerce payment method group rel qualifier persistence.
	 *
	 * @param commercePaymentMethodGroupRelQualifierPersistence the commerce payment method group rel qualifier persistence
	 */
	public void setCommercePaymentMethodGroupRelQualifierPersistence(
		CommercePaymentMethodGroupRelQualifierPersistence
			commercePaymentMethodGroupRelQualifierPersistence) {

		this.commercePaymentMethodGroupRelQualifierPersistence =
			commercePaymentMethodGroupRelQualifierPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		_setServiceUtilService(commercePaymentMethodGroupRelQualifierService);
	}

	public void destroy() {
		_setServiceUtilService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CommercePaymentMethodGroupRelQualifierService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CommercePaymentMethodGroupRelQualifier.class;
	}

	protected String getModelClassName() {
		return CommercePaymentMethodGroupRelQualifier.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				commercePaymentMethodGroupRelQualifierPersistence.
					getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		CommercePaymentMethodGroupRelQualifierService
			commercePaymentMethodGroupRelQualifierService) {

		try {
			Field field =
				CommercePaymentMethodGroupRelQualifierServiceUtil.class.
					getDeclaredField("_service");

			field.setAccessible(true);

			field.set(null, commercePaymentMethodGroupRelQualifierService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@BeanReference(
		type = com.liferay.commerce.payment.service.CommercePaymentMethodGroupRelQualifierLocalService.class
	)
	protected com.liferay.commerce.payment.service.
		CommercePaymentMethodGroupRelQualifierLocalService
			commercePaymentMethodGroupRelQualifierLocalService;

	@BeanReference(type = CommercePaymentMethodGroupRelQualifierService.class)
	protected CommercePaymentMethodGroupRelQualifierService
		commercePaymentMethodGroupRelQualifierService;

	@BeanReference(
		type = CommercePaymentMethodGroupRelQualifierPersistence.class
	)
	protected CommercePaymentMethodGroupRelQualifierPersistence
		commercePaymentMethodGroupRelQualifierPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

}