components:
    schemas:
        DispatchTrigger:
            properties:
                active:
                    type: boolean
                companyId:
                    format: int64
                    type: integer
                cronExpression:
                    type: string
                dispatchTaskClusterMode:
                    type: integer
                dispatchTaskExecutorType:
                    type: string
                dispatchTaskSettings:
                    additionalProperties: true
                    type: object
                endDate:
                    format: date
                    readOnly: true
                    type: string
                externalReferenceCode:
                    type: string
                id:
                    format: int64
                    type: integer
                name:
                    type: string
                overlapAllowed:
                    type: boolean
                startDate:
                    format: date
                    readOnly: true
                    type: string
                system:
                    type: boolean
                timeZoneId:
                    type: string
                userId:
                    format: int64
                    type: integer
info:
    description:
        "A Java client JAR is available for use with the group ID 'com.liferay', artifact ID
        'com.liferay.dispatch.rest.client', and version '1.0.0'."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: ""
    version: v1.0
openapi: 3.0.1
paths:
    "/dispatch-triggers":
        get:
            operationId: getDispatchTriggersPage
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/DispatchTrigger"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/DispatchTrigger"
                                type: array
            tags: ["DispatchTrigger"]
        post:
            operationId: postDispatchTrigger
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/DispatchTrigger"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/DispatchTrigger"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/DispatchTrigger"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/DispatchTrigger"
            tags: ["DispatchTrigger"]
    "/dispatch-triggers/{dispatchTriggerId}/run":
        post:
            operationId: postDispatchTriggerRun
            parameters:
                - in: path
                  name: dispatchTriggerId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["DispatchTrigger"]