create index IX_73F4DA4E on WikiNode (companyId, ctCollectionId);
create index IX_99D34 on WikiNode (companyId, status, ctCollectionId);
create index IX_5B8458D0 on WikiNode (groupId, ctCollectionId);
create unique index IX_7FF2268B on WikiNode (groupId, externalReferenceCode[$COLUMN_LENGTH:75$]);
create unique index IX_A83A2D0F on WikiNode (groupId, name[$COLUMN_LENGTH:75$], ctCollectionId);
create index IX_E1FB79B6 on WikiNode (groupId, status, ctCollectionId);
create index IX_75C1CF8A on WikiNode (uuid_[$COLUMN_LENGTH:75$], companyId, ctCollectionId);
create index IX_ADC98BDA on WikiNode (uuid_[$COLUMN_LENGTH:75$], ctCollectionId);
create unique index IX_C9456D0C on WikiNode (uuid_[$COLUMN_LENGTH:75$], groupId, ctCollectionId);

create index IX_3BBB2CE1 on WikiPage (companyId, ctCollectionId);
create index IX_9A368D8E on WikiPage (format[$COLUMN_LENGTH:75$], ctCollectionId);
create index IX_F9179E36 on WikiPage (groupId, externalReferenceCode[$COLUMN_LENGTH:75$], ctCollectionId);
create unique index IX_20D8C78E on WikiPage (groupId, externalReferenceCode[$COLUMN_LENGTH:75$], version, ctCollectionId);
create index IX_BA611D68 on WikiPage (groupId, nodeId, head, ctCollectionId);
create index IX_C99D1AF8 on WikiPage (groupId, nodeId, head, parentTitle[$COLUMN_LENGTH:255$], status, ctCollectionId);
create index IX_1276264E on WikiPage (groupId, nodeId, head, status, ctCollectionId);
create index IX_204860FA on WikiPage (groupId, nodeId, status, ctCollectionId);
create index IX_DE426744 on WikiPage (groupId, nodeId, title[$COLUMN_LENGTH:255$], head, ctCollectionId);
create index IX_C54CBC34 on WikiPage (groupId, userId, nodeId, status, ctCollectionId);
create index IX_2858EED4 on WikiPage (nodeId, ctCollectionId);
create index IX_A2603828 on WikiPage (nodeId, head, ctCollectionId);
create index IX_2766B952 on WikiPage (nodeId, head, parentTitle[$COLUMN_LENGTH:255$], ctCollectionId);
create index IX_A03E3838 on WikiPage (nodeId, head, parentTitle[$COLUMN_LENGTH:255$], status, ctCollectionId);
create index IX_F4D644E0 on WikiPage (nodeId, head, redirectTitle[$COLUMN_LENGTH:255$], ctCollectionId);
create index IX_F4E855C6 on WikiPage (nodeId, head, redirectTitle[$COLUMN_LENGTH:255$], status, ctCollectionId);
create index IX_B20E810E on WikiPage (nodeId, head, status, ctCollectionId);
create index IX_82C93A26 on WikiPage (nodeId, parentTitle[$COLUMN_LENGTH:255$], ctCollectionId);
create index IX_19BE0B4 on WikiPage (nodeId, redirectTitle[$COLUMN_LENGTH:255$], ctCollectionId);
create index IX_4EBCBBA on WikiPage (nodeId, status, ctCollectionId);
create index IX_E0C7E030 on WikiPage (nodeId, title[$COLUMN_LENGTH:255$], ctCollectionId);
create index IX_90D3B484 on WikiPage (nodeId, title[$COLUMN_LENGTH:255$], head, ctCollectionId);
create index IX_2471A116 on WikiPage (nodeId, title[$COLUMN_LENGTH:255$], status, ctCollectionId);
create unique index IX_149A1ED4 on WikiPage (nodeId, title[$COLUMN_LENGTH:255$], version, ctCollectionId);
create index IX_F886F6D4 on WikiPage (resourcePrimKey, ctCollectionId);
create index IX_856045C5 on WikiPage (resourcePrimKey, nodeId, ctCollectionId);
create index IX_2CCD659 on WikiPage (resourcePrimKey, nodeId, head, ctCollectionId);
create index IX_FCA9A1AB on WikiPage (resourcePrimKey, nodeId, status, ctCollectionId);
create unique index IX_436230DF on WikiPage (resourcePrimKey, nodeId, version, ctCollectionId);
create index IX_EA91D3BA on WikiPage (resourcePrimKey, status, ctCollectionId);
create index IX_E03966F4 on WikiPage (userId, nodeId, status, ctCollectionId);
create index IX_49E80197 on WikiPage (uuid_[$COLUMN_LENGTH:75$], companyId, ctCollectionId);
create index IX_80EE1FED on WikiPage (uuid_[$COLUMN_LENGTH:75$], ctCollectionId);
create unique index IX_D57ABE59 on WikiPage (uuid_[$COLUMN_LENGTH:75$], groupId, ctCollectionId);

create unique index IX_574104C2 on WikiPageResource (nodeId, title[$COLUMN_LENGTH:255$], ctCollectionId);
create index IX_256EBBC5 on WikiPageResource (uuid_[$COLUMN_LENGTH:75$], companyId, ctCollectionId);
create index IX_CA95F67F on WikiPageResource (uuid_[$COLUMN_LENGTH:75$], ctCollectionId);
create unique index IX_2E262C07 on WikiPageResource (uuid_[$COLUMN_LENGTH:75$], groupId, ctCollectionId);