/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.inventory.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CommerceInventoryWarehouseRel service. Represents a row in the &quot;CIWarehouseRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.commerce.inventory.model.impl.CommerceInventoryWarehouseRelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.commerce.inventory.model.impl.CommerceInventoryWarehouseRelImpl</code>.
 * </p>
 *
 * @author Luca Pellizzon
 * @see CommerceInventoryWarehouseRel
 * @generated
 */
@ProviderType
public interface CommerceInventoryWarehouseRelModel
	extends AttachedModel, AuditedModel,
			BaseModel<CommerceInventoryWarehouseRel>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a commerce inventory warehouse rel model instance should use the {@link CommerceInventoryWarehouseRel} interface instead.
	 */

	/**
	 * Returns the primary key of this commerce inventory warehouse rel.
	 *
	 * @return the primary key of this commerce inventory warehouse rel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this commerce inventory warehouse rel.
	 *
	 * @param primaryKey the primary key of this commerce inventory warehouse rel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this commerce inventory warehouse rel.
	 *
	 * @return the mvcc version of this commerce inventory warehouse rel
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this commerce inventory warehouse rel.
	 *
	 * @param mvccVersion the mvcc version of this commerce inventory warehouse rel
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the commerce inventory warehouse rel ID of this commerce inventory warehouse rel.
	 *
	 * @return the commerce inventory warehouse rel ID of this commerce inventory warehouse rel
	 */
	public long getCommerceInventoryWarehouseRelId();

	/**
	 * Sets the commerce inventory warehouse rel ID of this commerce inventory warehouse rel.
	 *
	 * @param commerceInventoryWarehouseRelId the commerce inventory warehouse rel ID of this commerce inventory warehouse rel
	 */
	public void setCommerceInventoryWarehouseRelId(
		long commerceInventoryWarehouseRelId);

	/**
	 * Returns the company ID of this commerce inventory warehouse rel.
	 *
	 * @return the company ID of this commerce inventory warehouse rel
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this commerce inventory warehouse rel.
	 *
	 * @param companyId the company ID of this commerce inventory warehouse rel
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this commerce inventory warehouse rel.
	 *
	 * @return the user ID of this commerce inventory warehouse rel
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this commerce inventory warehouse rel.
	 *
	 * @param userId the user ID of this commerce inventory warehouse rel
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this commerce inventory warehouse rel.
	 *
	 * @return the user uuid of this commerce inventory warehouse rel
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this commerce inventory warehouse rel.
	 *
	 * @param userUuid the user uuid of this commerce inventory warehouse rel
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this commerce inventory warehouse rel.
	 *
	 * @return the user name of this commerce inventory warehouse rel
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this commerce inventory warehouse rel.
	 *
	 * @param userName the user name of this commerce inventory warehouse rel
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this commerce inventory warehouse rel.
	 *
	 * @return the create date of this commerce inventory warehouse rel
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this commerce inventory warehouse rel.
	 *
	 * @param createDate the create date of this commerce inventory warehouse rel
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this commerce inventory warehouse rel.
	 *
	 * @return the modified date of this commerce inventory warehouse rel
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this commerce inventory warehouse rel.
	 *
	 * @param modifiedDate the modified date of this commerce inventory warehouse rel
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this commerce inventory warehouse rel.
	 *
	 * @return the fully qualified class name of this commerce inventory warehouse rel
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this commerce inventory warehouse rel.
	 *
	 * @return the class name ID of this commerce inventory warehouse rel
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this commerce inventory warehouse rel.
	 *
	 * @param classNameId the class name ID of this commerce inventory warehouse rel
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this commerce inventory warehouse rel.
	 *
	 * @return the class pk of this commerce inventory warehouse rel
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this commerce inventory warehouse rel.
	 *
	 * @param classPK the class pk of this commerce inventory warehouse rel
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the commerce inventory warehouse ID of this commerce inventory warehouse rel.
	 *
	 * @return the commerce inventory warehouse ID of this commerce inventory warehouse rel
	 */
	public long getCommerceInventoryWarehouseId();

	/**
	 * Sets the commerce inventory warehouse ID of this commerce inventory warehouse rel.
	 *
	 * @param commerceInventoryWarehouseId the commerce inventory warehouse ID of this commerce inventory warehouse rel
	 */
	public void setCommerceInventoryWarehouseId(
		long commerceInventoryWarehouseId);

	@Override
	public CommerceInventoryWarehouseRel cloneWithOriginalValues();

}