/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.oauth.client.persistence.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.oauth.client.persistence.model.OAuthClientAuthServer;
import com.liferay.oauth.client.persistence.model.OAuthClientAuthServerModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the OAuthClientAuthServer service. Represents a row in the &quot;OAuthClientAuthServer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>OAuthClientAuthServerModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OAuthClientAuthServerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OAuthClientAuthServerImpl
 * @generated
 */
@JSON(strict = true)
public class OAuthClientAuthServerModelImpl
	extends BaseModelImpl<OAuthClientAuthServer>
	implements OAuthClientAuthServerModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a o auth client auth server model instance should use the <code>OAuthClientAuthServer</code> interface instead.
	 */
	public static final String TABLE_NAME = "OAuthClientAuthServer";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT},
		{"oAuthClientAuthServerId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"discoveryEndpoint", Types.VARCHAR}, {"issuer", Types.VARCHAR},
		{"metadataJSON", Types.CLOB}, {"type_", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("oAuthClientAuthServerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("discoveryEndpoint", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("issuer", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("metadataJSON", Types.CLOB);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OAuthClientAuthServer (mvccVersion LONG default 0 not null,oAuthClientAuthServerId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,discoveryEndpoint VARCHAR(256) null,issuer VARCHAR(128) null,metadataJSON TEXT null,type_ VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table OAuthClientAuthServer";

	public static final String ORDER_BY_JPQL =
		" ORDER BY oAuthClientAuthServer.oAuthClientAuthServerId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OAuthClientAuthServer.oAuthClientAuthServerId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ISSUER_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TYPE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long OAUTHCLIENTAUTHSERVERID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public OAuthClientAuthServerModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _oAuthClientAuthServerId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setOAuthClientAuthServerId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _oAuthClientAuthServerId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OAuthClientAuthServer.class;
	}

	@Override
	public String getModelClassName() {
		return OAuthClientAuthServer.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<OAuthClientAuthServer, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<OAuthClientAuthServer, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OAuthClientAuthServer, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((OAuthClientAuthServer)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<OAuthClientAuthServer, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<OAuthClientAuthServer, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(OAuthClientAuthServer)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<OAuthClientAuthServer, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<OAuthClientAuthServer, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<OAuthClientAuthServer, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<OAuthClientAuthServer, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<OAuthClientAuthServer, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<OAuthClientAuthServer, Object>>();
		Map<String, BiConsumer<OAuthClientAuthServer, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<OAuthClientAuthServer, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", OAuthClientAuthServer::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<OAuthClientAuthServer, Long>)
				OAuthClientAuthServer::setMvccVersion);
		attributeGetterFunctions.put(
			"oAuthClientAuthServerId",
			OAuthClientAuthServer::getOAuthClientAuthServerId);
		attributeSetterBiConsumers.put(
			"oAuthClientAuthServerId",
			(BiConsumer<OAuthClientAuthServer, Long>)
				OAuthClientAuthServer::setOAuthClientAuthServerId);
		attributeGetterFunctions.put(
			"companyId", OAuthClientAuthServer::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<OAuthClientAuthServer, Long>)
				OAuthClientAuthServer::setCompanyId);
		attributeGetterFunctions.put(
			"userId", OAuthClientAuthServer::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<OAuthClientAuthServer, Long>)
				OAuthClientAuthServer::setUserId);
		attributeGetterFunctions.put(
			"userName", OAuthClientAuthServer::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<OAuthClientAuthServer, String>)
				OAuthClientAuthServer::setUserName);
		attributeGetterFunctions.put(
			"createDate", OAuthClientAuthServer::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<OAuthClientAuthServer, Date>)
				OAuthClientAuthServer::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", OAuthClientAuthServer::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<OAuthClientAuthServer, Date>)
				OAuthClientAuthServer::setModifiedDate);
		attributeGetterFunctions.put(
			"discoveryEndpoint", OAuthClientAuthServer::getDiscoveryEndpoint);
		attributeSetterBiConsumers.put(
			"discoveryEndpoint",
			(BiConsumer<OAuthClientAuthServer, String>)
				OAuthClientAuthServer::setDiscoveryEndpoint);
		attributeGetterFunctions.put(
			"issuer", OAuthClientAuthServer::getIssuer);
		attributeSetterBiConsumers.put(
			"issuer",
			(BiConsumer<OAuthClientAuthServer, String>)
				OAuthClientAuthServer::setIssuer);
		attributeGetterFunctions.put(
			"metadataJSON", OAuthClientAuthServer::getMetadataJSON);
		attributeSetterBiConsumers.put(
			"metadataJSON",
			(BiConsumer<OAuthClientAuthServer, String>)
				OAuthClientAuthServer::setMetadataJSON);
		attributeGetterFunctions.put("type", OAuthClientAuthServer::getType);
		attributeSetterBiConsumers.put(
			"type",
			(BiConsumer<OAuthClientAuthServer, String>)
				OAuthClientAuthServer::setType);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getOAuthClientAuthServerId() {
		return _oAuthClientAuthServerId;
	}

	@Override
	public void setOAuthClientAuthServerId(long oAuthClientAuthServerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_oAuthClientAuthServerId = oAuthClientAuthServerId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getDiscoveryEndpoint() {
		if (_discoveryEndpoint == null) {
			return "";
		}
		else {
			return _discoveryEndpoint;
		}
	}

	@Override
	public void setDiscoveryEndpoint(String discoveryEndpoint) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_discoveryEndpoint = discoveryEndpoint;
	}

	@JSON
	@Override
	public String getIssuer() {
		if (_issuer == null) {
			return "";
		}
		else {
			return _issuer;
		}
	}

	@Override
	public void setIssuer(String issuer) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_issuer = issuer;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalIssuer() {
		return getColumnOriginalValue("issuer");
	}

	@JSON
	@Override
	public String getMetadataJSON() {
		if (_metadataJSON == null) {
			return "";
		}
		else {
			return _metadataJSON;
		}
	}

	@Override
	public void setMetadataJSON(String metadataJSON) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_metadataJSON = metadataJSON;
	}

	@JSON
	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalType() {
		return getColumnOriginalValue("type_");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), OAuthClientAuthServer.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public OAuthClientAuthServer toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, OAuthClientAuthServer>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OAuthClientAuthServerImpl oAuthClientAuthServerImpl =
			new OAuthClientAuthServerImpl();

		oAuthClientAuthServerImpl.setMvccVersion(getMvccVersion());
		oAuthClientAuthServerImpl.setOAuthClientAuthServerId(
			getOAuthClientAuthServerId());
		oAuthClientAuthServerImpl.setCompanyId(getCompanyId());
		oAuthClientAuthServerImpl.setUserId(getUserId());
		oAuthClientAuthServerImpl.setUserName(getUserName());
		oAuthClientAuthServerImpl.setCreateDate(getCreateDate());
		oAuthClientAuthServerImpl.setModifiedDate(getModifiedDate());
		oAuthClientAuthServerImpl.setDiscoveryEndpoint(getDiscoveryEndpoint());
		oAuthClientAuthServerImpl.setIssuer(getIssuer());
		oAuthClientAuthServerImpl.setMetadataJSON(getMetadataJSON());
		oAuthClientAuthServerImpl.setType(getType());

		oAuthClientAuthServerImpl.resetOriginalValues();

		return oAuthClientAuthServerImpl;
	}

	@Override
	public OAuthClientAuthServer cloneWithOriginalValues() {
		OAuthClientAuthServerImpl oAuthClientAuthServerImpl =
			new OAuthClientAuthServerImpl();

		oAuthClientAuthServerImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		oAuthClientAuthServerImpl.setOAuthClientAuthServerId(
			this.<Long>getColumnOriginalValue("oAuthClientAuthServerId"));
		oAuthClientAuthServerImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		oAuthClientAuthServerImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		oAuthClientAuthServerImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		oAuthClientAuthServerImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		oAuthClientAuthServerImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		oAuthClientAuthServerImpl.setDiscoveryEndpoint(
			this.<String>getColumnOriginalValue("discoveryEndpoint"));
		oAuthClientAuthServerImpl.setIssuer(
			this.<String>getColumnOriginalValue("issuer"));
		oAuthClientAuthServerImpl.setMetadataJSON(
			this.<String>getColumnOriginalValue("metadataJSON"));
		oAuthClientAuthServerImpl.setType(
			this.<String>getColumnOriginalValue("type_"));

		return oAuthClientAuthServerImpl;
	}

	@Override
	public int compareTo(OAuthClientAuthServer oAuthClientAuthServer) {
		long primaryKey = oAuthClientAuthServer.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof OAuthClientAuthServer)) {
			return false;
		}

		OAuthClientAuthServer oAuthClientAuthServer =
			(OAuthClientAuthServer)object;

		long primaryKey = oAuthClientAuthServer.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<OAuthClientAuthServer> toCacheModel() {
		OAuthClientAuthServerCacheModel oAuthClientAuthServerCacheModel =
			new OAuthClientAuthServerCacheModel();

		oAuthClientAuthServerCacheModel.mvccVersion = getMvccVersion();

		oAuthClientAuthServerCacheModel.oAuthClientAuthServerId =
			getOAuthClientAuthServerId();

		oAuthClientAuthServerCacheModel.companyId = getCompanyId();

		oAuthClientAuthServerCacheModel.userId = getUserId();

		oAuthClientAuthServerCacheModel.userName = getUserName();

		String userName = oAuthClientAuthServerCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			oAuthClientAuthServerCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			oAuthClientAuthServerCacheModel.createDate = createDate.getTime();
		}
		else {
			oAuthClientAuthServerCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			oAuthClientAuthServerCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			oAuthClientAuthServerCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		oAuthClientAuthServerCacheModel.discoveryEndpoint =
			getDiscoveryEndpoint();

		String discoveryEndpoint =
			oAuthClientAuthServerCacheModel.discoveryEndpoint;

		if ((discoveryEndpoint != null) && (discoveryEndpoint.length() == 0)) {
			oAuthClientAuthServerCacheModel.discoveryEndpoint = null;
		}

		oAuthClientAuthServerCacheModel.issuer = getIssuer();

		String issuer = oAuthClientAuthServerCacheModel.issuer;

		if ((issuer != null) && (issuer.length() == 0)) {
			oAuthClientAuthServerCacheModel.issuer = null;
		}

		oAuthClientAuthServerCacheModel.metadataJSON = getMetadataJSON();

		String metadataJSON = oAuthClientAuthServerCacheModel.metadataJSON;

		if ((metadataJSON != null) && (metadataJSON.length() == 0)) {
			oAuthClientAuthServerCacheModel.metadataJSON = null;
		}

		oAuthClientAuthServerCacheModel.type = getType();

		String type = oAuthClientAuthServerCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			oAuthClientAuthServerCacheModel.type = null;
		}

		return oAuthClientAuthServerCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<OAuthClientAuthServer, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<OAuthClientAuthServer, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OAuthClientAuthServer, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(OAuthClientAuthServer)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<OAuthClientAuthServer, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<OAuthClientAuthServer, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OAuthClientAuthServer, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((OAuthClientAuthServer)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, OAuthClientAuthServer>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					OAuthClientAuthServer.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _oAuthClientAuthServerId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _discoveryEndpoint;
	private String _issuer;
	private String _metadataJSON;
	private String _type;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<OAuthClientAuthServer, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((OAuthClientAuthServer)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"oAuthClientAuthServerId", _oAuthClientAuthServerId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("discoveryEndpoint", _discoveryEndpoint);
		_columnOriginalValues.put("issuer", _issuer);
		_columnOriginalValues.put("metadataJSON", _metadataJSON);
		_columnOriginalValues.put("type_", _type);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("oAuthClientAuthServerId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("discoveryEndpoint", 128L);

		columnBitmasks.put("issuer", 256L);

		columnBitmasks.put("metadataJSON", 512L);

		columnBitmasks.put("type_", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private OAuthClientAuthServer _escapedModel;

}