export default function getNewActivity() {
	return {
		activityPromotion: '',
		ad: '',
		assetsLiferayRequired: '',
		budgets: [],
		description: '',
		endDate: '',
		gatedLandingPage: '',
		goalOfContent: '',
		howLiferayBrandUsed: '',
		keywordsForPPCCampaigns: '',
		leadFollowUpStrategies: [],
		leadGenerated: '',
		liferayBranding: '',
		liferayParticipationRequirements: '',
		location: '',
		marketingActivity: '',
		mdfRequestAmount: '',
		name: '',
		overallMessageContentCTA: '',
		primaryThemeOrMessage: '',
		r_tacticToActivities_c_tacticId: '',
		r_typeActivityToActivities_c_typeActivityId: '',
		sourceAndSizeOfInviteeList: '',
		specificSites: '',
		startDate: '',
		targetofLeads: '',
		totalCostOfExpense: '',
	};
}
