/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.model.RedundantIndexEntry;
import com.liferay.portal.tools.service.builder.test.model.RedundantIndexEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RedundantIndexEntry service. Represents a row in the &quot;RedundantIndexEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RedundantIndexEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RedundantIndexEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RedundantIndexEntryImpl
 * @generated
 */
public class RedundantIndexEntryModelImpl
	extends BaseModelImpl<RedundantIndexEntry>
	implements RedundantIndexEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a redundant index entry model instance should use the <code>RedundantIndexEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "RedundantIndexEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"redundantIndexEntryId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("redundantIndexEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table RedundantIndexEntry (redundantIndexEntryId LONG not null primary key,companyId LONG,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table RedundantIndexEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY redundantIndexEntry.redundantIndexEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY RedundantIndexEntry.redundantIndexEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long REDUNDANTINDEXENTRYID_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.model.RedundantIndexEntry"));

	public RedundantIndexEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _redundantIndexEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRedundantIndexEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _redundantIndexEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RedundantIndexEntry.class;
	}

	@Override
	public String getModelClassName() {
		return RedundantIndexEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RedundantIndexEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RedundantIndexEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RedundantIndexEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RedundantIndexEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RedundantIndexEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RedundantIndexEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RedundantIndexEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RedundantIndexEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RedundantIndexEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<RedundantIndexEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<RedundantIndexEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<RedundantIndexEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<RedundantIndexEntry, Object>>();
		Map<String, BiConsumer<RedundantIndexEntry, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<RedundantIndexEntry, ?>>();

		attributeGetterFunctions.put(
			"redundantIndexEntryId",
			RedundantIndexEntry::getRedundantIndexEntryId);
		attributeSetterBiConsumers.put(
			"redundantIndexEntryId",
			(BiConsumer<RedundantIndexEntry, Long>)
				RedundantIndexEntry::setRedundantIndexEntryId);
		attributeGetterFunctions.put(
			"companyId", RedundantIndexEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<RedundantIndexEntry, Long>)
				RedundantIndexEntry::setCompanyId);
		attributeGetterFunctions.put("name", RedundantIndexEntry::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<RedundantIndexEntry, String>)
				RedundantIndexEntry::setName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getRedundantIndexEntryId() {
		return _redundantIndexEntryId;
	}

	@Override
	public void setRedundantIndexEntryId(long redundantIndexEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_redundantIndexEntryId = redundantIndexEntryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), RedundantIndexEntry.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RedundantIndexEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RedundantIndexEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RedundantIndexEntryImpl redundantIndexEntryImpl =
			new RedundantIndexEntryImpl();

		redundantIndexEntryImpl.setRedundantIndexEntryId(
			getRedundantIndexEntryId());
		redundantIndexEntryImpl.setCompanyId(getCompanyId());
		redundantIndexEntryImpl.setName(getName());

		redundantIndexEntryImpl.resetOriginalValues();

		return redundantIndexEntryImpl;
	}

	@Override
	public RedundantIndexEntry cloneWithOriginalValues() {
		RedundantIndexEntryImpl redundantIndexEntryImpl =
			new RedundantIndexEntryImpl();

		redundantIndexEntryImpl.setRedundantIndexEntryId(
			this.<Long>getColumnOriginalValue("redundantIndexEntryId"));
		redundantIndexEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		redundantIndexEntryImpl.setName(
			this.<String>getColumnOriginalValue("name"));

		return redundantIndexEntryImpl;
	}

	@Override
	public int compareTo(RedundantIndexEntry redundantIndexEntry) {
		long primaryKey = redundantIndexEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RedundantIndexEntry)) {
			return false;
		}

		RedundantIndexEntry redundantIndexEntry = (RedundantIndexEntry)object;

		long primaryKey = redundantIndexEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RedundantIndexEntry> toCacheModel() {
		RedundantIndexEntryCacheModel redundantIndexEntryCacheModel =
			new RedundantIndexEntryCacheModel();

		redundantIndexEntryCacheModel.redundantIndexEntryId =
			getRedundantIndexEntryId();

		redundantIndexEntryCacheModel.companyId = getCompanyId();

		redundantIndexEntryCacheModel.name = getName();

		String name = redundantIndexEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			redundantIndexEntryCacheModel.name = null;
		}

		return redundantIndexEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RedundantIndexEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RedundantIndexEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RedundantIndexEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(RedundantIndexEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, RedundantIndexEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					RedundantIndexEntry.class, ModelWrapper.class);

	}

	private long _redundantIndexEntryId;
	private long _companyId;
	private String _name;

	public <T> T getColumnValue(String columnName) {
		Function<RedundantIndexEntry, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((RedundantIndexEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"redundantIndexEntryId", _redundantIndexEntryId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("name", _name);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("redundantIndexEntryId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("name", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private RedundantIndexEntry _escapedModel;

}