create table NotificationsQueueEntry (
	mvccVersion LONG default 0 not null,
	notificationsQueueEntryId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	classNameId LONG,
	classPK LONG,
	notificationsTemplateId LONG,
	from_ VARCHAR(75) null,
	fromName VARCHAR(75) null,
	to_ VARCHAR(75) null,
	toName VARCHAR(75) null,
	cc VARCHAR(75) null,
	bcc VARCHAR(75) null,
	subject VARCHAR(75) null,
	body VARCHAR(75) null,
	priority DOUBLE,
	sent BOOLEAN,
	sentDate DATE null
);

create table NotificationsTemplate (
	mvccVersion LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	notificationsTemplateId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	name STRING null,
	description VARCHAR(75) null,
	from_ VARCHAR(75) null,
	fromName STRING null,
	to_ VARCHAR(75) null,
	cc VARCHAR(75) null,
	bcc VARCHAR(75) null,
	enabled BOOLEAN,
	subject STRING null,
	body STRING null
);